package com.adzerk.android.sdk.rest;

import com.google.gson.JsonObject;

import java.util.List;
import java.util.Map;

/**
 * Contains the key to identify the User in a {@link Response}
 * <p>
 * The response contains the key used to identify the unique user that places the request. All user keys
 * are generated by the API. You can target to a user when you place a {@link Request}.
 *
 * Not supported:
 * - pendingConversions, partnerUserIds, retargettingSegments
 * - cookieMonster, dirtyCookies
 */
public class User  {

    String key;

    boolean isNew;

    List<String> interests;

    JsonObject custom;

    boolean optOut;

    Map<String, List<Integer>> blockedItems;

    Map<Integer, List<Long>> flightViewTimes;

    Map<Integer, List<Long>> adViewTimes;

    Map<Integer, List<Long>> siteViewTimes;


    /**
     * Creates User with specified key.
     * @param key identifies user
     */
    public User(String key) {
        this.key = key;
    }

    /**
     * Returns the key that identifies the user placing a {@link Request}
     * @return user key
     */
    public String getKey() {
        return key;
    }

    public boolean isNew() {
        return isNew;
    }

    public List<String> getInterests() {
        return interests;
    }

    public JsonObject getCustom() {
        return custom;
    }

    public boolean isOptOut() {
        return optOut;
    }

    public Map<String, List<Integer>> getBlockedItems() {
        return blockedItems;
    }

    public Map<Integer, List<Long>> getFlightViewTimes() {
        return flightViewTimes;
    }

    public Map<Integer, List<Long>> getAdViewTimes() {
        return adViewTimes;
    }

    public Map<Integer, List<Long>> getSiteViewTimes() {
        return siteViewTimes;
    }
}
