package com.adzerk.android.sdk.rest;

/**
 * Contains the key to identify the User in a {@link Response}
 * <p>
 * The response contains the key used to identify the unique user that places the request. All user keys
 * are generated by the API. You can target to a user when you place a {@link Request}.
 */
public class User  {

    String key;

    /**
     * Creates User with specified key.
     * @param key identifies user
     */
    public User(String key) {
        this.key = key;
    }

    /**
     * Returns the key that identifies the user placing a {@link Request}
     * @return user key
     */
    public String getKey() {
        return key;
    }
}
